- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "DevSevOps with AWS"
    DURATION: 140
    IS_LIVE: true
    DETAILS:
      MONTHS: 4
      TRAINER: "Shiva"
    TOPICS:
    - Linux
    - Ansible
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: |
        Program: {{ PROGRAM }}
        Duration: {{ DURATION }}
        is_live: {{ IS_LIVE }}
        Details: {{ DETAILS }}
        topics: {{ TOPICS }}
    
